package com.security;

public class BucketPolicySamples {


    public static String BucketPolicy1 = "{\n"
            + "  \"Version\":\"2012-10-17\",\n"
            + "  \"Statement\":[\n"
            + "    {\n"
            + "      \"Sid\":\"AddPerm\",\n"
            + "      \"Effect\":\"Allow\",\n"
            + "      \"Principal\": \"*\",\n"
            + "      \"Action\":[\"s3:GetObject\"],\n"
            + "      \"Resource\":[\"arn:aws:s3:::examplebucket/*\"]\n"
            + "    }\n"
            + "  ]\n"
            + "}";


    public static String BucketPolicy2 = "{\n"
            + "  \"Version\":\"2012-10-17\",\n"
            + "  \"Statement\":[\n"
            + "    {\n"
            + "      \"Sid\":\"AddPerm\",\n"
            + "      \"Effect\":\"Allow\",\n"
            + "      \"Principal\": {\"AWS\":\"*\"},\n"
            + "      \"Action\":[\"s3:GetObject\"],\n"
            + "      \"Resource\":[\"arn:aws:s3:::examplebucket/*\"]\n"
            + "    }\n"
            + "  ]\n"
            + "}";

    public static String BucketPolicy3 = "{\n"
            + "  \"Version\":\"2012-10-17\",\n"
            + "  \"Statement\":[\n"
            + "    {\n"
            + "      \"Sid\":\"AddCannedAcl\",\n"
            + "      \"Effect\":\"Allow\",\n"
            + "      \"Principal\": {\"AWS\": [\"arn:aws:iam::111122223333:root\",\"arn:aws:iam::444455556666:root\"]},\n"
            + "      \"Action\":[\"s3:PutObject\",\"s3:PutObjectAcl\"],\n"
            + "      \"Resource\":[\"arn:aws:s3:::examplebucket/*\"],\n"
            + "      \"Condition\":{\"StringEquals\":{\"s3:x-amz-acl\":[\"public-read\"]}}\n"
            + "    }\n"
            + "  ]\n"
            + "}";

    public static String BucketPolicy4 = "{\n"
            + "  \"Version\": \"2012-10-17\",\n"
            + "  \"Id\": \"S3PolicyId1\",\n"
            + "  \"Statement\": [\n"
            + "    {\n"
            + "      \"Sid\": \"IPAllow\",\n"
            + "      \"Effect\": \"Allow\",\n"
            + "      \"Principal\": \"*\",\n"
            + "      \"Action\": \"s3:*\",\n"
            + "      \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "      \"Condition\": {\n"
            + "         \"IpAddress\": {\"aws:SourceIp\": \"54.240.143.0/24\"},\n"
            + "         \"NotIpAddress\": {\"aws:SourceIp\": \"54.240.143.188/32\"} \n"
            + "      } \n"
            + "    } \n"
            + "  ]\n"
            + "}";

    public static String BucketPolicy5 = "{\n"
            + "  \"Version\": \"2012-10-17\",\n"
            + "  \"Id\": \"S3PolicyId1\",\n"
            + "  \"Statement\": [\n"
            + "    {\n"
            + "      \"Sid\": \"IPAllow\",\n"
            + "      \"Effect\": \"Allow\",\n"
            + "      \"Principal\": \"*\",\n"
            + "      \"Action\": \"s3:*\",\n"
            + "      \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "      \"Condition\": {\n"
            + "         \"IpAddress\": {\"aws:SourceIp\": \"0.0.0.0/0\"},\n"
            + "         \"NotIpAddress\": {\"aws:SourceIp\": \"54.240.143.188/32\"} \n"
            + "      } \n"
            + "    } \n"
            + "  ]\n"
            + "}";

    public static String BucketPolicy6 = "{\n"
            + "  \"Version\": \"2012-10-17\",\n"
            + "  \"Id\": \"S3PolicyId1\",\n"
            + "  \"Statement\": [\n"
            + "    {\n"
            + "      \"Sid\": \"IPAllow\",\n"
            + "      \"Effect\": \"Allow\",\n"
            + "      \"Principal\": \"*\",\n"
            + "      \"Action\": \"s3:*\",\n"
            + "      \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "      \"Condition\": {\n"
            + "         \"IpAddress\": {\"aws:SourceIp\": \"0.0.0.0/0\"},\n"
            + "         \"NotIpAddress\": {\"aws:SourceIp\": \"0.0.0.0/0\"} \n"
            + "      } \n"
            + "    } \n"
            + "  ]\n"
            + "}";


    public static String BucketPolicy7 = "{\n"
            + "    \"Version\": \"2012-10-17\",\n"
            + "    \"Statement\": [\n"
            + "        {\n"
            + "            \"Sid\": \"AddPerm\",\n"
            + "            \"Effect\": \"Allow\",\n"
            + "            \"Principal\": \"*\",\n"
            + "            \"Action\": \"*\",\n"
            + "            \"Resource\": \"arn:aws:s3:::examplebucket/test01\",\n"
            + "            \"Condition\": {\n"
            + "                \"NotIpAddress\": {\n"
            + "                    \"aws:SourceIp\": \"0.0.0.0/0\"\n"
            + "                },\n"
            + "                \"IpAddress\": {\n"
            + "                    \"aws:SourceIp\": \"0.0.0.0/0\"\n"
            + "                }\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"Sid\": \"AddPerm\",\n"
            + "            \"Effect\": \"Deny\",\n"
            + "            \"Principal\": \"*\",\n"
            + "            \"Action\": \"*\",\n"
            + "            \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "            \"Condition\": {\n"
            + "                \"IpAddress\": {\n"
            + "                    \"aws:SourceIp\": \"0.0.0.0/0\"\n"
            + "                }\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"Sid\": \"AddPerm\",\n"
            + "            \"Effect\": \"Allow\",\n"
            + "            \"Principal\": \"*\",\n"
            + "            \"Action\": \"*\",\n"
            + "            \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "            \"Condition\": {\n"
            + "                \"IpAddress\": {\n"
            + "                    \"aws:SourceIp\": \"0.0.0.0/0\"\n"
            + "                }\n"
            + "            }\n"
            + "        }\n"
            + "    ]\n"
            + "}";

    public static String BucketPolicy8 = "{\n"
            + "    \"Version\": \"2012-10-17\",\n"
            + "    \"Id\": \"http referer policy example\",\n"
            + "    \"Statement\": [\n"
            + "        {\n"
            + "            \"Sid\": \"Allow get requests originating from www.example.com and example.com.\",\n"
            + "            \"Effect\": \"Allow\",\n"
            + "            \"Principal\": \"*\",\n"
            + "            \"Action\": \"s3:GetObject\",\n"
            + "            \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "            \"Condition\": {\n"
            + "                \"StringLike\": {\n"
            + "                    \"aws:Referer\": [\n"
            + "                        \"http://www.example.com/*\",\n"
            + "                        \"http://example.com/*\"\n"
            + "                    ]\n"
            + "                }\n"
            + "            }\n"
            + "        }\n"
            + "    ]\n"
            + "}";


    public static String BucketPolicy9 = "{\n"
            + "   \"Version\": \"2012-10-17\",\n"
            + "   \"Id\": \"http referer policy example\",\n"
            + "   \"Statement\": [\n"
            + "     {\n"
            + "       \"Sid\": \"Allow get requests referred by www.example.com and example.com.\",\n"
            + "       \"Effect\": \"Allow\",\n"
            + "       \"Principal\": \"*\",\n"
            + "       \"Action\": \"s3:GetObject\",\n"
            + "       \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "       \"Condition\": {\n"
            + "         \"StringLike\": {\"aws:Referer\": [\"http://www.example.com/*\",\"http://example.com/*\"]}\n"
            + "       }\n"
            + "     },\n"
            + "      {\n"
            + "        \"Sid\": \"Explicit deny to ensure requests are allowed only from specific referer.\",\n"
            + "        \"Effect\": \"Deny\",\n"
            + "        \"Principal\": \"*\",\n"
            + "        \"Action\": \"s3:*\",\n"
            + "        \"Resource\": \"arn:aws:s3:::examplebucket/*\",\n"
            + "        \"Condition\": {\n"
            + "          \"StringNotLike\": {\"aws:Referer\": [\"http://www.example.com/*\",\"http://example.com/*\"]}\n"
            + "        }\n"
            + "      }\n"
            + "   ]\n"
            + "}";


    public static String BucketPolicy10 = "{\n"
            + "  \"Version\":\"2012-10-17\",\n"
            + "  \"Statement\":[\n"
            + "    {\n"
            + "      \"Sid\":\"InventoryAndAnalyticsExamplePolicy\",\n"
            + "      \"Effect\":\"Allow\",\n"
            + "      \"Principal\": {\"Service\": \"s3.amazonaws.com\"},\n"
            + "      \"Action\":[\"s3:PutObject\"],\n"
            + "      \"Resource\":[\"arn:aws:s3:::destination-bucket/*\"],\n"
            + "      \"Condition\": {\n"
            + "          \"ArnLike\": {\n"
            + "              \"aws:SourceArn\": \"arn:aws:s3:::source-bucket\"\n"
            + "           },\n"
            + "         \"StringEquals\": {\n"
            + "             \"aws:SourceAccount\": \"1234567890\",\n"
            + "             \"s3:x-amz-acl\": \"bucket-owner-full-control\"\n"
            + "          }\n"
            + "       }\n"
            + "    }\n"
            + "  ]\n"
            + "}";
}
